events {}

http {

server {
    listen 80;
    server_name jenkins.local;

    location / {
        proxy_pass http://localhost:8080;
    }
}

server {
    listen 80;
    server_name sonarqube.local;

    location / {
        proxy_pass http://localhost:9000;
    }
}

}